name: debug
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  pull_request:

jobs:
  pytest:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]
    name: ubuntu - py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout tool repository
        uses: actions/checkout@v3
        with:
          repository: LABSN/sound-ci-helpers
          path: sound-ci-helpers
      - name: Create virtual sound card
        run: ./sound-ci-helpers/auto.sh
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools wheel
          python -m pip install --progress-bar off numpy sounddevice
      - name: Display system information
        run: python -m sounddevice
      - name: Try to play a sound
        run: python -c "import sounddevice as sd; import numpy as np; sd.play(np.random.randn(96000, 2), samplerate=48000, mapping=[1,2])"
      - name: Install package
        run: python -m pip install --progress-bar off main/.[test]
      - name: Try to play a sound
        run: python -c "from stimuli.audio import Tone; sound = Tone(100); sound.play()"
      - name: Try with pytest
        run: pytest main/debug/test_debug.py
      - name: Try part of the test suit
        run: pytest main/stimuli/audio/tests/test_tone.py
