name: doc
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout tool repository
        uses: actions/checkout@v3
        with:
          repository: LABSN/sound-ci-helpers
          path: sound-ci-helpers
      - name: Create virtual sound card
        run: ./sound-ci-helpers/auto.sh
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Install package
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools wheel
          python -m pip install --progress-bar off main/.[doc]
      - name: Build doc
        run: |
          cd ./main/doc
          make html
