name: doc
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ./main
      - name: Checkout tool repository
        uses: actions/checkout@v4
        with:
          repository: LABSN/sound-ci-helpers
          path: ./sound-ci-helpers
      - name: Create virtual sound card
        run: ./sound-ci-helpers/auto.sh
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          architecture: 'x64'
      - name: Install package
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools wheel
          python -m pip install --progress-bar off main/.[doc]
      - name: Display system information
        run: stimuli-sys_info --developer
      - name: Build doc
        run: make -C main/doc html
      - name: Prune sphinx environment
        run: rm -R ./main/doc/_build/html/.doctrees
      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: doc-dev
          path: ./main/doc/_build/html

  deploy:
    if: github.event_name == 'push'
    needs: build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download documentation
        uses: actions/download-artifact@v4
        with:
          name: doc-dev
          path: ./doc-dev
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./doc-dev
          target-folder: ./dev
          git-config-name: 'github-actions[bot]'
          git-config-email: 'github-actions[bot]@users.noreply.github.com'
          single-commit: true
          force: true
