name: pytest
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  pull_request:
    paths:
      - '**.py'
  push:
    branches: [main]
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  pytest:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        python-version: [3.8, 3.9, "3.10", "3.11"]
    name: ${{ matrix.os }} - py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout tool repository
        if: ${{ matrix.os != 'macos'}}
        uses: actions/checkout@v3
        with:
          repository: LABSN/sound-ci-helpers
          path: sound-ci-helpers
      - name: Create virtual sound card
        if: ${{ matrix.os != 'macos'}}
        run: ./sound-ci-helpers/auto.sh
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Install package
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools wheel
          python -m pip install --progress-bar off main/.[test]
      - name: Display system information
        run: stimuli-sys_info --developer
      - name: Run pytest
        run: pytest main/stimuli --cov=main/stimuli --cov-report=xml --cov-config=main/pyproject.toml
      - name: Upload to codecov
        if: ${{ matrix.os == 'ubuntu' && matrix.python-version == 3.9 }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage.xml
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
